# Generated by Django 3.0.5 on 2020-10-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_joblisting_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
