# Generated by Django 3.1.3 on 2020-11-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20201116_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='image',
            field=models.ImageField(blank=True, default='/static/extra-images/employer-2.png', null=True, upload_to='media'),
        ),
    ]
